### ISSUE TITLE
Behavior when foreign corporations are included

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#2225]
When I include a corporation but don't include the expansion it comes from, some strange scenarios can result.

* Valley Trust should work normally. It should still let you choose and play a Prelude card - this doesn't cause any weird situations like the other cases, and the balance is no different. Assuming that the player chose it, that is obviously what they expected to happen, and today they can only beg to restart the game.

* Four corporations essentially become dead draws: Morning Star, Aphrodite, Poseidon, Septem Tribus. You can barely even *contrive* a scenario where a player would choose one on purpose. And the danger is that a player might see the corp and not realize the expansion isn't in play, and torpedo their entire game. Recommendation: make it impossible to even click them without their expansion selected.

* I think Celestic should be put in that category as well even though it can technically work as long as *Colonies* is in.

* Aridor is still reasonably usable, and I have actually included it and played it in non-Colonies games, because it's the effect that is the interesting part. But instead of giving you a mandatory first action that does nothing, it should just not give you a mandatory first action at all.

**Comment by kevinb9n** [comment]
> But instead of giving you a mandatory first action that does nothing, it should just not give you a mandatory first action at all.

This part also applies to Vitor in a solo game.

**Comment by ap3h3ad** [comment]
Tbh I don't know why you would include corporations and not include the expansions that they belong to. In my opinion the game should just completely prevent that behaviour (so that you have to choose the expansions first and the corporation options change on that basis), not just for the four corporations you listed. I mean, if you only have the base game in your shelf you can't just add the Venus Next corporations and leave out the other Venus Cards and the Venus Board. 

Actually I don't understand that first point of yours. How should Valley Trust allow picking Prelude cards when the expansion is not in the game? In that case there are not Prelude cards in the game.

**Comment by kevinb9n** [comment]
> Tbh I don't know why you would include corporations and not include the expansions that they belong to. In my opinion the game should just completely prevent that behaviour (so that you have to choose the expansions first and the corporation options change on that basis), not just for the four corporations you listed. I mean, if you only have the base game in your shelf you can't just add the Venus Next corporations and leave out the other Venus Cards and the Venus Board.

Can you mention an advantage of this approach?

> Actually I don't understand that first point of yours. How should Valley Trust allow picking Prelude cards when the expansion is not in the game? In that case there are not Prelude cards in the game.

I understand you'd prefer this was not allowed. I'm talking about the current situation where it is allowed. Given that a user can choose it, there is actually nothing confusing or misleading or wrong with allowing that user to fetch three Prelude cards out of the box in the same way Aridor fetches more colony tiles out of the box. They are really just green cards (that are pink).

**Comment by ap3h3ad** [comment]
Maybe this is just a misunderstanding. Currently I think that if you do what you stated (add the Prelude corporations but NOT the Prelude expansion to a game) the game won't add the Prelude cards to the game cards, so they will just be missing. Of course you can correct me if I'm wrong here, because I didn't look into the code for a long time now. If this is the case how do you plan to fix the problem with Valley Trust? A fix would mean that Valley Trust could actually provide the player with Prelude cards, but they wouldn't be in the game (again... just correct me). So I don't really see why you would want to give the player the possibility to play a corporation without the expansion it belongs to. If you just prevent the game from making the corporation available without the expansion being active you don't have to worry about which corporations are actually useful without it's expansion and which are not.

**Comment by kevinb9n** [comment]
I'd rather focus on where we agree first, because I think the long discussion is gonna make people think "oh, controversial" and ignore it.

The two easiest ways to resolve this bug would probably be

* prevent any corp from being included without its expansion
* prevent only the 7 mentioned here from being included without its expansion

I could always file separately why I think Aridor and VT should still work, and if that was seen as super low priority I couldn't really blame anyone.

**Comment by andylatto** [comment]
I think preventing a corp from being included without its expansion would be a terrible idea. I play with a group of 20+ people who play with a variety of expansions, but alway allow all corps (except  the ones which don't work, like septum tribus without turmoil), and we all enjoy playing that way. The idea that this should be prohibited, so that we would have to fork the server and constantly merge to get future updates and expansions, because someone thinks that playing Viron without Venus is so unbalanced that it should be banned even if we explicitly check a box that says we want to allow it, seems ludicrous. There are far more unbalance corporations, including unofficial community ones, that are allowed; why should this be banned?

**Comment by kevinb9n** [comment]
Thanks. I felt obligated to acknowledge that it is indeed one of two ways to close this bug, but I also disagree with it and I think a lot of people would.

I think we should support this whether it's officially allowed or not, but in fact it even IS officially condoned besides:

<img width=500 src=https://user-images.githubusercontent.com/934551/106825504-df45e180-6639-11eb-868e-8b90d2686617.png>

That's the Prelude english rulebook.

So I hope this bug is resolved by making *only* the 7 special cases be unselectable without their parent expansions.

(Again, if that happens then I will still argue afterward to fix and reinclude Valley Trust. It seems entirely obvious to me how they expected VT to work when they wrote the rules passage above. Of course they assume the group would say "guess we'd better fish 3 prelude cards outta the box them." But for now, banned would be much better than "game-over" broken as it is currently. End tangent.)

**Comment by kevinb9n** [comment]
Spun off the Valley Trust part to #2833 as it is far more serious than the rest.

**Comment by kberg** [comment]
New UI is being put in place which warns players that corps might not be compatible, and that strange results might occur. #4394. With that warning, if a player still wants to proceed, caveat emptor. Changes could be made but they can not at least not be expected.

**Comment by kberg** [comment]
Even though I plan to close this bug, If there is still an interest in outright banning, please update this bug, and I'll make sure it's reopened.
