### ISSUE TITLE
Critical bug: Reds tax policy can be avoided if players spend all the remaining mc on a card when it is possible to use alternative payment and save mc

### ISSUE THREAD

**Issue by vsrisuknimit** [terraforming-mars/terraforming-mars#3007]
![image](https://user-images.githubusercontent.com/14239220/112148096-d4c4b480-8bb3-11eb-8d99-8e4aa390c785.png)

**Comment by vsrisuknimit** [comment]
<img width="896" alt="Screen Shot 2021-03-30 at 12 59 07 PM" src="https://user-images.githubusercontent.com/14239220/113027284-e4b23a80-9157-11eb-975e-dbf57574d03b.png">

<img width="1227" alt="Screen Shot 2021-03-30 at 12 59 57 PM" src="https://user-images.githubusercontent.com/14239220/113027308-eb40b200-9157-11eb-8c8a-bdaa65246e51.png">

<img width="840" alt="Screen Shot 2021-03-30 at 12 59 38 PM" src="https://user-images.githubusercontent.com/14239220/113027296-e7ad2b00-9157-11eb-9e78-3b9782e1ce4c.png">

Verified. It is reproducible.

**Comment by vsrisuknimit** [comment]
It is NOT about:
- Mars being terraformed.
- Raising Venus
- Media Group

It IS about:
- Dirigible
- Reds policy

Here is how it happened.
1) Just before the payment, player has enough floater on dirigible and mc to pay for the cost of the card + 3 mc for Reds tax. For example, 2 floater (6 mc equivalent) + 10 mc in cash to pay for Air Scrapping Expedition 13 mc + 3 mc Reds tax.
2) Instead of paying with 2 floater and leaving 7 mc behind, the player can pay with 1 floater and 10 mc, leaving no mc behind.
3) Venus is raised. No mc. Reds tax happened but no mc to take.
4) (Optional) Media group kicks in, giving 3 mc.

Implication:
This problem should also apply to all non-mc payment methods. Including just titanium.

<img width="458" alt="Screen Shot 2021-03-30 at 1 26 20 PM" src="https://user-images.githubusercontent.com/14239220/113030471-a0c13480-915b-11eb-895a-c2c2edea5bb1.png">

In the image above, the player should not be allowed to spend all their mc.

Proposed solution:

The canAfford is working properly, in this case. 

We should force the player to leave 3 mc behind for the reds tax in this case. Or more if they are playing other TR-raising cards. We should fix default payment.

**Comment by kberg** [comment]
This has been broadly mitigated with the `{tr}` attribute, including `Air Scrappers.` However there are still many areas where the reds tax can be avoided (eg TR bonus from planetary tracks.)

This can also be further mitigated on card play by including the reds tax in `reserveUnits`, but I fear that will put is more squarely on the other side, where cards are unplayable when they should be, if only you could execute them in order.

Once there's a cleaner undo (something that lets you merely 'reset this action', it would be good to put tighter screws on the reds tax, by failing at `increaseTerraformRating` as mentioned in #3732

Closing this, as it describes an edge case that is a function of the decision to err on making cards playable rather than unplayable.
