### ISSUE TITLE
Robotic Workforce: proc MarsU first?

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#3251]
When playing RW it would be super nice if it could process my Olympus and Mars Univ effects first before I have to choose which prod to copy, because they can be information-gaining.

**Comment by kevinb9n** [comment]
Okay: it _does_ do Olympus Conf first, just not Mars U.

**Comment by bafolts** [comment]
I _think_ we would have to pass the `-1` argument [here](https://github.com/bafolts/terraforming-mars/commit/fd94395e2cae3185978c530603651e9ab4f68e07). This should then have the action for Mars U run before the RW action. The -1 is picking a number for comparison within the `DeferredActionQueue`. We should set this up so that the number is less than the priority given to robotic workforce instead of `-1`. Using `-1` would suffice for the time being.

**Comment by kberg** [comment]
I suspect this is no longer a problem.

Olympus Conference's effect has priority SUPERPOWER(-1)
Mars U's effect has priority DISCARD_BEFORE_DRAW(3)
Robotic Workforce's play action has priority DEFAULT(8)

I've written a test that verifies this.
