### ISSUE TITLE
ApiWaitingFor test timing out

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#3299]
1) ApiWaitingFor
       fails when player not found:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/kberg/git/terraforming-mars/build/tests/routes/ApiWaitingFor.spec.js)
 
Could just be me. But I want to look in to why this happens.

**Comment by bafolts** [comment]
The `fails when player not found` test is not an async test. I am surprised this error was observed. Since javascript is single threaded and this test is not asynchronous I am not sure how it was timed out. @kberg were there local changes on your branch when this was observed or was it on the `main` branch?

**Comment by kberg** [comment]
There were local changes but they did not seem relevant.

>

**Comment by kberg** [comment]
This seems to happen rarely.
