### ISSUE TITLE
Add a warning indicator for a blue card action that results in partial/meaningless resolution (like Search for Life "alien face")

### ISSUE THREAD

**Issue by erisalke** [terraforming-mars/terraforming-mars#3552]
It's an idea for interface and user experience improvement.
For cards like:
- Aquifer Pumping (ocean for cash or steel)
- Water from Europe (oceans cash/titan)
- GHG bacteria (temperature for microbes)
- Venus Magnetiser (Venus for power plant)
- Water Splitting Plant (oxygen for electricity)
and similar. Once a corresponding track (oxygen, temperature, oceans or Venus) is already completed the blue card could indicate a warning that taking the card's action will results only in partial or meaningless resolution. E.g. Aquifer Pumping still provides the bonus metals but no oceans or TM points will be granted for this action. 
Of course the player may still be interested in taking this action nevertheless. But it would be nice to have some clear indicator that "* terms and conditions apply".
Same thing as what Search for Life does with the green alien face when it has at least 1 token on it

**Comment by kberg** [comment]
Today is "make sure every open bug has a comment" day!

This would be a useful behavior, I agree. It's unfortunately not high on the priority list. I think there's room for not only adding information about these cards (that is, explaining that these cards are playable, have no effect, and only serve to delay the game) and cards that aren't playable (that is, cards you expect to be playable, but aren't, because for instance the player can't afford the Reds tax.)

**Comment by kberg** [comment]
I think this is actually fixed! Warnings of this type have been present for a few months now. If some are missing, let me know. (I'm trying to leave them particularly high level, but there's room for adding useful warnings.)
