### ISSUE TITLE
Option for improvements to asynchronous play, delay off-turn choices until player turn

### ISSUE THREAD

**Issue by BeriAlpha** [terraforming-mars/terraforming-mars#3688]
Suggestion: Add an option during game setup to delay anything that requires a player's response off-turn until the start of their next turn.

This would include:
- Gaining resources from Philares
- Gaining resources as a colony bonus when another player trades (ex: Miranda)

That might actually be it. I can't think of anything else that requires an off-turn response.

If this option is enabled, then when one of these situations causes a player to gain a resource, rather than the active player's turn pausing until they make their decision, the game remembers the decisions they need to make and asks them to make the decisions at the start of their next turn.

In extreme cases, a player could have 5 or more decisions to make, so the game needs to remember them all and ask the player to make those choices sequentially.

**Comment by nwai90** [comment]
@BeriAlpha This could be done as a feature toggle, but also introduces some subtle edge cases. For example you may want another player to gain resources immediately so that you can remove them (e.g. asteroid cards, attack cards like Virus, Sabotage etc.)

**Comment by kberg** [comment]
That's exactly what I was thinking

**Comment by kberg** [comment]
Gotcha.

**Comment by SliceOfBread** [comment]
What about drafting? From memory, it waits until everyone makes a card selection and then shows everyone the passed cards. These could also be queued up. I know for the PBF (BGG play-by-forum) people, they never draft as it takes too long and I'd assume a similar situation for async players.

**Comment by kberg** [comment]
There are some technical problems in the way - for instance it's possible
for an action saved for another player to be completely lost if the system
reboots. I actually think it would be moderately complicated to do this
correctly, only because of the way the app is structured today.

I know this isn't going to be a popular suggestion, but if you know how to
code, you might be able to make this happen for your own local server. Do I
love that suggestion? No I don't.

>

**Comment by BeriAlpha** [comment]
It's a fair suggestion, but far outside my skill set. Thanks for looking
into it!

**Comment by fuerchter** [comment]
Hello,
I hope we're not getting too far off-topic here, but I've been running both your email_notify and customized_server branches on a Heroku setup. There are some instances, where this implementation doesn't work well, imo:
1. When a player takes an action and it's still their turn afterwards (obvious example is taking their first action), they receive an E-Mail. At that point, they clearly already know it's still their turn and it comes across as spammy/unpolished.
2. When the Heroku server is restarted or wakes up from sleeping Player.setWaitingFor() will be executed again, sending another E-Mail notification.
3. Entering the E-Mail address into the "Player name" field is unintuitive, and should probably have it's own UI.

I've tried to find some kind of solution to this, with [process.uptime()](https://nodejs.org/api/process.html#processuptime), or Timer.startedAt, Game.activePlayer, or saving the previous waitingFor. Ultimately, I don't know the code well enough here, and am not capable to work on these myself.

I would love, if there was a more device-agnostic/async-friendly way to notify players other than what's in [WaitingFor.vue](https://github.com/terraforming-mars/terraforming-mars/blob/424394e77e73e2054bb1173b7392a25f79b6d48f/src/client/components/WaitingFor.vue#L116) (but I obviously don't have a say in this). The other relevant issues I know of, were: #3123 #3899

**Comment by bafolts** [comment]
I am not familiar with `email_notify` or `customized_server`. Those seem to be forks maintained by @puuj.  What I would recommend for the first problem mentioned is to not send an e-mail to a user if they have taken an action and they will take the next action.

For part two the code that is e-mailing could not send e-mails when a game is being deserialized.

For part three that will require a change to that fork.

Issue #3899 is something we should fix soon. On android devices users will either not see the notification or the runtime exception that gets thrown could be causing other side effects.

The asynchronous play is a weak point of this project as the hobby plans on heroku servers can restart without notice or go idle. I think  the problems you mention here of not notifying the user are addressable though. To address the problem with the server being able to go down without notice and come back up would require significant changes to our server code. Often times when a user has to take an action we have functions holding a lot of state. We would need to rewrite this in a way so that we are never waiting on a function as we can't serialize a function.

**Comment by puuj** [comment]
Thanks for the feedback @fuerchter. Glad someone found those forks useful. Also, definitely tag me in the future so I remember to check comments. My main goal was to have a low impact integration of notifications so as the main projected updated merging would be relatively low effort, hence the lack of bells and whistles.  Some thoughts inline.
 
>     1. When a player takes an action and it's still their turn afterwards (obvious example is taking their first action), they receive an E-Mail. At that point, they clearly already know it's still their turn and it comes across as spammy/unpolished.

This should be relatively easy to fix by tracking the last acting player in the game state. On the other hand, it waits a minute before sending that e-mail and if you've taken over a minute to take your turn, maybe you should get a nudge?

>     2. When the Heroku server is restarted or wakes up from sleeping Player.setWaitingFor() will be 
executed again, sending another E-Mail notification.

This is a valid issue and also harder to fix. It basically needs the code that sets up notifications to be aware of how the action is invoked. I'll look into the process.uptime() value to see if that can help identify a restart. I don't host on Heroku, so no promises it will work in that environment.

>     3. Entering the E-Mail address into the "Player name" field is unintuitive, and should probably have it's own UI.

This is more security by obfuscation than a deliberate choice. Ideally the user would opt-in and provide their e-mail address when starting the game and then verify it with some other link before any e-mail gets sent.  I can imagine something like what the rebalanced project does for claiming one-time use links for that process. That's a pretty heavy lift. Otherwise, there's no real way to prevent people from putting any random e-mail and getting the server blocked. I'll consider adding the e-mail field and hopefully it doesn't get abused?

**Comment by fuerchter** [comment]
I suggest we continue this in discord DMs, since it's not immediately relevant to the main project (I think we're both in the project's discord so finding each other should not be difficult). I might not come around to writing up the questions I have immediately though, more towards the weekend.

**Comment by kberg** [comment]
At this stage, and after all this time, I don't see this being done, so I'm going to close the issue.
