### ISSUE TITLE
Remove non-determinism from shuffling

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#3739]
>  Has anyone reported the Reshuffle-Drafting bug?  Our 4p game got the draft for the next generation and did not have 16 cards left in the deck, so it needed a reshuffle. One player did not select a card before the next server restart, so it forgot all the other players' selections and dealt us a DIFFERENT set of 4 cards!
>
> So if I do not like any of my choices and two or more of the cards would be great for the next player, I can do nothing for 24 hours and get choices which may be better for me and worse for him.

#2132 is related to this discussion.

**Comment by bafolts** [comment]
We should start on storing a number for each card instead of the card name in the serialized classes. With that in place we could then store the ordered version of Dealer.discarded and perhaps another field for a shuffled version of discarded. We could shuffle it as we add items to discarded. Then no matter when we end up exhausting the deck the shuffled version of discarded would be the same.

**Comment by kberg** [comment]
I believe I've got this mostly handled. Things that remain unmanaged by the seeded randomizer.
* Global Event Deck
* Random Political Agendas 
* Milestone award selector
* Random board selection

I think this is good enough. As long as the app remains stable, the saved seed will provide the same deck. Game structure does change, of course, but this is best effort.
