### ISSUE TITLE
Ability Clear database and games-overview page of old unfinished games

### ISSUE THREAD

**Issue by Aquariu** [terraforming-mars/terraforming-mars#4282]
Dear all,

I'm not sure if this should be considered a feature request...

How can I, as the server admin delete from the db the old games that were never finished or games that were started mistakenly ?
I see these games in the games overview page but can't find any way in the web ui to delete them.
Is there one way that I've missed ? Would it be a usefull feature ?

Sorry if that question was asked already but I couldn't find anything in the issues.

Regards,

Olivier

**Comment by nwai90** [comment]
Currently there is no way to delete games directly from the UI. What you can do is to set the env variable `MAX_GAME_DAYS`, so that games older than the given value are automatically purged.

**Comment by kberg** [comment]
https://github.com/terraforming-mars/terraforming-mars/wiki/dot-env describes that the environment variable `MAX_GAME_DAYS` has a default value of 10. So even if you do nothing, you will get the purge you were looking for.

I'm marking this as closed, because I think there is no technical work to be done, but let us know if you have questions.
