### ISSUE TITLE
Mars University / Sponsored Academies interaction

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#4313]
You would always want to discard-1-get-3 first before you decide whether to discard-1-get-1. Something changed and is doing these in the opposite order now.

**Comment by kevinb9n** [comment]
Happening with MarsU / Invention Contest too, so this may be a widespread thing.

**Comment by kberg** [comment]
Mars U had the wrong priority (DEFAULT) and now has the same priority as Sponsored Academies (discard before draw.) This means they have equivalent priorities and now are just a matter of some non-determinstic behavior (eg which card was played first.)

It also occurs before Invetion Contest, which is pure draw. I agree that the order there should change, and instead of 

* Discard before draw
* Draw

The order should be

* Draw
* Discard before draw
* Draw dependent on discard

Then again, the order could just be draw, then discard, and only create the second draw after the discard. Hmm.

**Comment by kberg** [comment]
None of that takes into account fully resolving sponsored academies over mars u, though.

**Comment by kevinb9n** [comment]
If it helps, you could put Mars U in a different category, "optional discard before draw".

**Comment by kberg** [comment]
> If it helps, you could put Mars U in a different category, "optional discard before draw".

That's pretty much what I plan to do, despite not really liking it. I fear the slippery slope.
