### ISSUE TITLE
Undo - drawing new card allows you to see what will be drawn again.

### ISSUE THREAD

**Issue by dennenboom17** [terraforming-mars/terraforming-mars#4317]
Thanks for this version of TM, it is great thanks so much.

We noticed an issue on the drawing cards and the undo action.

- Any time you draw a card and undo the action, only available on first action, the card goes back to the pile.  The next person will draw the same card and therefore you will know what card they could of taken.  Should the undo randomize the card back to the draw pile?
- On research this will randomize the cards.

**Comment by kevinb9n** [comment]
See #1846

**Comment by kberg** [comment]
It will be hard to adopt any solution that randomizes on undo because it breaks the determinsim we hope to have with game seeds. Any ability to undo after card draw, even if it randomizes information, does not eliminate that the player now knows a certain card is not in play (and in fact, is probably buried where someone else can't get it.)

IMO the ideal situation is that undo is allowable up until a player gains information, and at that point, the player may not undo.

I think it is appropriate to close this as a duplicate and follow along on #1846

**Comment by dennenboom17** [comment]
Thanks you
