### ISSUE TITLE
Add "source" to the download / upload game settings JSON file

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#4399]
>  Json is not uploading correctly. I have an entry:
> "solarPhaseOption": false,
> When I upload it, World Government Terraforming is turned on. When I upload it again, it is turned off.

This happens when someone downloads from one server and uploads to another.

I suggest that we add a "source" field to the JSON that represents the host URL. And on upload, if the host doesn't match the server, provide a warning before applying the changes.

**Comment by AnnaMinasian** [comment]
Hey, I found this as a great `good first issue` and I've created a PR https://github.com/terraforming-mars/terraforming-mars/pull/4418
Please give a feedback if I should do it in other way.

**Comment by kberg** [comment]
@AnnaMinasian thank you!

I realized after writing this that I really should have thought about this a bit -- many players are going to be surprised by the change, and this might be a mistake to implement. I will read it carefully and provide feedback, though probably not for another day.

**Comment by prvit** [comment]
@kberg hey, I was looking for a `first issue` as well. 
I am trying to understand the issue itself. 
1) Is it more about logically not correct setting's state, like some setting being contradictory to another? 
2) Or is it caused by different forks/versions of the source code, like if somebody uses a game where there is no some setting, then downloads json there and try to upload it to the version of the game with the setting. And this would most probably lead to turning it off by default, but that might be not what user expects?

In both cases it's possible to check each and every setting coming from an uploaded json, make some decisions based on it. But it seems like a bit an over engineering here as for me.

What if for case 1) We can define all contradictory settings, check only them and show an alert with more details?
But if it's more about 2). What about storing some kind of a current code base version in that json? If backward compatibility for settings will be maintained, we should show an alert only for empty and newer version on upload.

**Comment by kberg** [comment]
I'm going to close this. It's not a great first issue after all. Sorry for the false hope.
