### ISSUE TITLE
error 503

### ISSUE THREAD

**Issue by Albinouze** [terraforming-mars/terraforming-mars#4656]
Game unplayable for quite some time. Not related to the other issue I oppened today.
See screenshots, I don't know what triggers this nor how it solves itself... I have no other info than the screenshots
Thank you for your work :)

![app_error](https://user-images.githubusercontent.com/108677806/177996367-664ffd16-8ae7-43bb-9417-1956ae395423.JPG)
![F5](https://user-images.githubusercontent.com/108677806/177996370-6706673a-338e-402e-8d48-35091828f048.JPG)
.

**Comment by kberg** [comment]
This happens when the server restarts. Yesterday we had a couple of planned restarts while trying to diagnose some big issues. Sorry about this. This is a known issue, particularly that game state is only _mostly_ preserved during restart.

There was a planned outage announcement on discord, it just wasn't widely distributed.
![image](https://user-images.githubusercontent.com/413481/178111997-9083b80d-9d6e-47f1-a553-fb75018bf1b2.png)

**Comment by kberg** [comment]
Thank you for these reports.

**Comment by Albinouze** [comment]
Hello, this issue occurs more frequently lastly (for the last week or 2 maybe).

The message on white screen:
Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

exemple: https://terraforming-mars.herokuapp.com/player?id=p9f866044715b&noredirect
