### ISSUE TITLE
Corporation draft with limited corporations might not work

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#4741]
From Discord:
> FoxRageQc: HEllo, when i try to create a game today, it says this: Internal server error: No more corporation cards for game g1d08898d0861
> k9: @FoxRageQc did you try corporations draft with a limimted set of corporations?
> FoxRageQc: Hmmm yes i think so

**Comment by pauliimmonen** [comment]
I did a little investigation of the issue. The error message derives from corporations draft mode. The error happens because as we initialize each player the corporations are dealt to them. So as we start drafting "minimum corporations required" amount is already popped out of the deck. As a result you need double the minimum to get the corporations draft going.

**Comment by kberg** [comment]
Thanks, @pauliimmonen. I think #4928 will fix this as it gives you a deck of corporations no matter how many you start with.

**Comment by kberg** [comment]
This is fixed.
