### ISSUE TITLE
Player's available actions should not include Standard Actions if they cannot afford any

### ISSUE THREAD

**Issue by jepowers** [terraforming-mars/terraforming-mars#4862]
On a player's turn, the list of available actions shouldn't include "Standard Projects" if the player can't afford to perform any of the standard projects.

<img width="303" alt="image" src="https://user-images.githubusercontent.com/24195375/188023940-9b2ff2ec-d721-4007-96ed-49ea1ecc9b01.png">

**Comment by kberg** [comment]
Yeah, I hear you.

I believe the reason it was done this way is because you otherwise cannot see the costs of the standard projects to understand whether you can or cannot afford them. Recently this was changed so that "standard projects" wasn't selected if it was the top item in the menu, at least as an accommodation.

Unless you have new information to add about why this should just be removed, it's best to close this issue.

**Comment by jepowers** [comment]
I'm not quite sure I understand, but it's been a looong day so go easy on me if this is a big duh on my part.

Couldn't there just be a function that compares the least-expensive standard project's cost with the player's available megacredits? For instance, in a basic game if the player has fewer than 11 mc (the cost of Power Plant), the function would return false and Standard Projects would not. be shown as an available action?

Thanks for all your contributions, btw. I wish I was a better programmer and could take action on some of the ideas my friends and I have.

**Comment by Dislexsick** [comment]
I think it may be worthwhile doing something that hides, or otherwise makes it clear that this option has nothing viable behind it, in a way that's consistent with the rest of the interface - or if not inconsistent, does so in a way that's clear.

For instance, when nil standard projects are available any of following (inc. multiple) could be used:
1. Change the text to a lighter shade of grey
2. Add a small message below the option stating ("You cannot afford any standard projects right now.")
3. Put the standard projects option to the bottom of the list when nil are affordable.

Alterantively, is there any reason to not have Standard Projects displayed in the interface, just like milestones, awards, colonies, etc?  If they clutter it too much perhaps an option for the player to hide them?

**Comment by kberg** [comment]
I'd like to avoid another configuration option. The three numbered options
are all decent. I have my own personal ranking of preference (I've even
already considered one of them, but not the other two.) But any of those
will do.

**Comment by Dislexsick** [comment]
Actually, you may just be able to disregard all of this.  The solution appears to have already been implemented anyway -- I went to snag a screenshot to mock up what I meant, and I noticed the Standard Projects option was not appearing.
Switching Learner Mode back on (I had it off) brought it back.

I think that right there is the solution, in line with your messaging above @kberg I'd like to offer a refinement as a solution to @jepowers 

"Standard Projects is displayed, even when you cannot afford them as a learning aide to newer players to remind them that they exist, and so they can view the costs of them.  If you are experienced enough at the game that you do not need these, switching off Learner Mode and refreshing will remove the option when it cannot be afforded"

![image](https://user-images.githubusercontent.com/14899418/188045976-eadf9fa5-bcb2-46e5-84e6-c0791d6488be.png)

**Comment by jepowers** [comment]
> I believe the reason it was done this way is because you otherwise cannot see the costs of the standard projects to understand whether you can or cannot afford them.

This is what I don't get. Why is it important for a player to be able to select that action and see the costs? A reasonable player would assume that it's not listed or available for the same reason that any of the other unlisted actions are not available, i.e. they don't meet the requirements necessary to take that action. 

I'd actually argue that it's counterintuitive to leave it as an available action, because for a brief second a player might believe they've miscalculated and that there ARE in fact still standard projects they can afford, only to be met with disappointment and frustration when they select that action and see that nope, they actually can't. 

The frustration of clicking for naught far outweighs the need to personally see that you can't afford any of the actions, imho. Especially when you consider that they can click the info button and see the standard project costs if they really feel the need.

**Comment by Dislexsick** [comment]
> Why is it important for a player to be able to select that action and see the costs?

People know the game to varying degrees.  I do not have the standard project costs perfectly memorised for instance (despite this, I have learner mode off, because if I care about a standard project it's for a specific reason).  
I personally do know I can access the help to see it, but not everyone knows this.

> A reasonable player would assume that it's not listed or available for the same reason that any of the other unlisted actions are not available

This is the behaviour I have observed exhibited when Learner Mode is turned off.  I was totally with you at the start of the issue, thinking "Yeah, it's annoying that the option shows up when it's not applicable!".  I actually think given the Learner Mode option covers this option and it ends up hidden, per what you want, it's totally fair to have it shown, exclusively when Learner Mode is still enabled -- If you've graduated to not needing to see it and other aides, then switching off Learner Mode seems like the right call, until that time it will stay there reminding you of core rules of the game.

**Comment by kberg** [comment]
By the way, part of the problem space includes the fan expansion variants. I'm not saying those should drive the need, but they're definitely in there.

(e.g. alt venus standard project, and the costs for the Moon standard projects.)

**Comment by kberg** [comment]
> 

Yes, I hear you. This discussion was had and this was the compromise we came up with. I really am sorry you don't like it, but we had to draw the line somewhere, and this was the line we drew.

I can still consider other options, but it is not likely that one of them is removing the item altogether.

**Comment by jepowers** [comment]
I honestly had no idea there _was_ a Learner Mode. Where is this setting? Based on what you're saying, it sounds like my entire group has unwittingly been playing as Learners this whole time. If that's the case, I'm totally happy with it.

**Comment by kberg** [comment]
![image](https://user-images.githubusercontent.com/413481/188050160-0a722c8e-9afb-4ee3-b57d-0513305538d6.png)

Click that gear.

And you'll see this

![image](https://user-images.githubusercontent.com/413481/188050229-3d56506c-6059-4a89-98af-52cda7daf040.png)

**Comment by Dislexsick** [comment]
Learner mode: Hit up the little Cog icon.  Also while there familiarise yourself with the others -- One is help, which is good to direct newer players to anyway, as it includes player aides; and the other shows you important settings and info for current game! :)

![image](https://user-images.githubusercontent.com/14899418/188050319-6715c0e2-796d-4392-925a-ee43f97b4d23.png)

**Comment by Dislexsick** [comment]
> By the way, part of the problem space includes the fan expansion variants. I'm not saying those should drive the need, but they're definitely in there.
> 
> (e.g. alt venus standard project, and the costs for the Moon standard projects.)

There is, at the cost of a level of dev effort needed, a way to solve all of this in a unified and consistent manner -- but it's a whole new feature as opposed to just looking at this issue.

I think there could be benefit showing somewhere (Even if not prominent, e.g. at the bottom, below where colonies would be shown) all of the actions and standard projects that are available in this game.  
Some could change contextually, for instance:

- Text referring to Ecoline, only if Ecoline were present in the game; 
- Trade would not appear if Colonies was not being used
- End Your Turn may dissapear when Fast Mode is enabled.
- The standard projects would only show those under the current config, including changing to alt Venus

![image](https://user-images.githubusercontent.com/14899418/188052063-6462e660-aa85-4a58-8c23-e3fa9231f34a.png)

**Comment by jepowers** [comment]
Oh geez. I'm embarrassed to say that I've never noticed that mode listed there, despite having clicked on the settings cog numerous times. 

I still feel like showing it at all feels out of step with the rest of the UX, but it's not something I'm invested in now that I know there's an option to turn it off.

**Comment by kberg** [comment]
> I still feel like showing it at all feels out of step with the rest of the UX, but it's not something I'm invested in now that I know there's an option to turn it off.

That's because it _is_ out of step with the rest of the UX. There's about a thousand of things that are out of step with each other. Organic growth that came out of the Pandemic, and no single UX leadership and all that.
