### ISSUE TITLE
Rules error: Should reshuffle draw pile when empty

### ISSUE THREAD

**Issue by BeriAlpha** [terraforming-mars/terraforming-mars#5163]
The draw pile should be reshuffled immediately when empty, rather than when you need to draw a card and there aren't any. There should never be 0 cards in the draw pile.

Source: Jacob Fryxelius https://boardgamegeek.com/thread/1652743/article/23975124#23975124
https://boardgamegeek.com/thread/1705209/article/24723217#24723217
"The deck is reshuffled from the discard pile if it becomes empty."

Further context as to how it affects the game: Both my friend and I ran into the 'Unexpected Empty Deck' error in our game. See also https://github.com/terraforming-mars/terraforming-mars/issues/4772
We were leaning heavily into card draw and engine-building, but this was a real game where we were both doing our best. I built up a ton of energy production, and right at the end, I put 58 energy into Hi-Tech Lab and picked up the entire deck.

Now that there are no cards in the draw pile, he attempted to play a card costing more than 20, and thanks to Spin-Off Department, he should have drawn a card. Instead, he got 'Unexpected Empty Deck' and the card didn't resolve correctly.
https://terraforming-mars.herokuapp.com/player?id=p4867e5837f01

I wanted to use the action of Asteroid Deflection System to reveal a card from the deck, and was also prevented from doing so by Unexpected Empty Deck.
https://terraforming-mars.herokuapp.com/player?id=pc12badb4bded

**Comment by kberg** [comment]
Today is "make sure every open bug has a comment" day!
This is a reasonable issue.

**Comment by linalana** [comment]
I'm considering tackling this as a first contribution to the project. @kberg  , do think this would be a reasonable intro issue for an experienced web developer?

**Comment by kberg** [comment]
Hey, this is a reasonable first issue. It's not a front end web issue of course, You can in theory, fix and test this without firing up a browser.

**Comment by linalana** [comment]
Cool. Yeah, I might look at this then. I'm interested in starting to contribute, but just generally going to state that it might happen that someone gets to it before me, so that's okay too.

**Comment by kberg** [comment]
There hasn't been a big rush to fix this, and now that you mention it, this is a perfect starter project where most of the work is focusing on the infrastructure.

(hint: `npm run build && npm run build:tests && npm run test:server` is probably the most efficient way to get started.

(After your first call to `npm run build`, `npm run build:server` will be a faster replacement.

If you have questions, hop on the discord.

**Comment by kberg** [comment]
(Most of the fix is in `src/server/cards/Deck.ts`. There's no really good unit test that you can copy from in `src/cards/Deck.spec.ts` so that's also a little tricky.

**Comment by lukenofurther** [comment]
Hi, I'm new around here and this looks like a nice issue to get started with. I've got everything working locally and had a quick reccy of the parts of the code and test file, looks like a good one to get going on. Would anyone mind if i give it a bash?

**Comment by kberg** [comment]
Yes, go for it! Thanks.

**Comment by lukenofurther** [comment]
Nice one thanks @kberg :)

I've been able to replicate the problem and found it's not actually a rules error, as far as I can tell. `Deck` already does reshuffle the discard pile to form a new draw pile as soon as it's empty (after a draw). It looks like it has done this since [its creation](https://github.com/terraforming-mars/terraforming-mars/commit/3c01e0883081b774301b1ccfd1a6a56a79eb9dd6) 15 months ago. 

The only way I've found to replicate the problems described in this issue and in #4772 is by emptying the discard pile, **as well as**, the draw pile. In this case, I was able to get `AsteroidDeflectionSystem` to throw the "Unexpected Empty Deck" error. So it looks like the problem only seems to arise when the draw pile is correctly empty because the discard was empty at the time the draw pile became empty. @BeriAlpha do you remember if that was the situation in the game you played?

Interestingly, I wasn't able to get `SpinOffDepartment` or `HiTechLab` to throw the error. I suspect because of the `DrawCards` [rewrite](https://github.com/terraforming-mars/terraforming-mars/pull/5902) 4 months ago, which seems to have fixed anything that uses `player.drawCard` or `player.drawCardKeepSome` to draw the card. In these cases I don't think any cards are drawn but no error is thrown.

`AsteroidDeflectionSystem` still errors because it uses `Deck`'s `draw` method directly. Presumably anything else that also does so will also encounter this error when encountering this quite niche scenario. One way to look at this is that `Deck.draw` isn't doing anything wrong here. However, it could handle it more gracefully, for example by returning undefined or throwing a new error class, e.g. `DeckEmptyOnDrawError`, either of which can be handled gracefully by whatever code is calling `draw`. The latter will be less intrusive for existing code but either way it's probably prudent to check that any part of the code that calls `draw` is able to handle the situation gracefully.

I'm very new to this codebase though so my knowledge on how this fits into the rest of the code is very generic.

**Comment by kberg** [comment]
Good research!

Deck.draw is used in 28 places.
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/7fc5556c-0888-420c-b7f3-bef7c9a4ce21)

DrawCards uses `drawCardsByCondition`, which I suppose is safer? I doubt it, to be honest. Because dCKS still returns potentially fewer cards than expected, and it ALSO uses `draw`:

![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/ce442013-3060-46f3-882c-46636d126691)

Perhaps the appropriate change is for `Deck.draw` to change from returning `T` to `T | undefined`. I wonder how that will change app flow.

**Comment by kberg** [comment]
One such fix might be to change Deck a little bit.

```
get length() {
    return this.drawPile.length;
  }

  public drawOrThrow(logger: Logger, source: 'top' | 'bottom' = 'top'): T {
    const card = this.draw(logger, source);
    if (card === undefined) {
      throw new Error('fix');
    }
    return card;
  }

  public draw(logger: Logger, source: 'top' | 'bottom' = 'top'): T | undefined {
    const card = source === 'top' ? this.drawPile.pop() : this.drawPile.shift();

    if (card === undefined) {
      return undefined;
    }
```

And then SearchForLife might change
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/3f7665d4-4a86-43e7-a059-eb0a904e1cd6)

**Comment by kberg** [comment]
Anyway, I'm not sure which is right. I like your idea about custom errors, though I haven't written custom error types.

**Comment by lukenofurther** [comment]
As you say `drawByCondition` is safe. That's because the condition on line 80 evaluates to true when there are no cards in the draw and discard piles, so the loop breaks before `draw` is ever called.

```ts
      if (discardedCards.size >= this.drawPile.length + this.discardPile.length) {
        logger.log(`discarded every ${this.type} card without a match`);
        break;
      }
```

Thinking about it, I prefer the option like you say - to have `draw` always return undefined rather than error when there is no card to draw. It makes more "semantic" sense - the function is saying "I'm returning undefined because there is no card to draw". The advantage of custom errors (best is a custom error class but could be some other identifying property) is they allow callees to respond to the type of exception thrown - but returning undefined indicates what's happened to the callee anyway.

The disadvantage of doing this is that all callees will need to change their code to handle the case where `draw` returns undefined - typescript will not allow it otherwise. Your idea of having `drawOrThrow` would get around that, it could be used instead for callees we're not wanting to deal with yet. Let me start going through that list of 28 and see how much work they are to change.

There's one other change that I think would be advantageous. In the situation where the draw pile is empty because when it emptied the discard pile was also empty, subsequent discards don't trigger an immediate reshuffle I don't believe, and they probably shouldn't (?). I don't think you'd do that in a real life game. In a real life game you'd probably just shuffle in the discard pile when next drawing again, right? If so, it'd make sense for `draw` to do the same thing.

**Comment by kberg** [comment]
There's no reason we can't do this with a series of steps, instead of all
at once.

For instance:
1. add method drawOrThrow
2. add legacyDraw, which is short for calling drawOrThrow.
3. Rename all uses of draw to call legacyDraw.
4. Change draw so it returns T | undefined.

5..33 Fix each card one at a time.
34: Remove legacyDraw

Steps 1-4 could be a single commit, or PR.

What you say about draw makes sense.

**Comment by lukenofurther** [comment]
Good plan 👍🏽

**Comment by lukenofurther** [comment]
One other thing. I notice `lodash` isn't included in this codebase - is that a conscious decision?

**Comment by kberg** [comment]
It is a conscious decision. I've read about lodash and underscore a few times, and felt that if it had better first-class typescript support I'd consider one or the other. Once something like lodash enters the repo, it's hard to get rid of it, so I've been reluctant to just add it.

mnemonist is a good case where it had a far better version of Multiset than I originally wrote, and it eventually replaced my implementation.

**Comment by lukenofurther** [comment]
@kberg I commonly use `lodash` in projects. I find it's very useful for cutting down on custom code for certain operations, as well as allowing a less imperative coding style, which personally I find very valuable. I've found the TS support provided in its types package is good, not perfect but good.

But anyway, I understand your misgivings so no worries. I've not heard of mnemonist before, it looks very nice.

**Comment by lukenofurther** [comment]
@kberg I've opened a draft PR with some initial changes https://github.com/terraforming-mars/terraforming-mars/pull/6315

**Comment by lukenofurther** [comment]
Btw @kberg have you ever considered adding a mocking library like [sinon](https://sinonjs.org/)?

**Comment by kberg** [comment]
Yeah. Sinon was added in
https://github.com/terraforming-mars/terraforming-mars/pull/3396 and
removed in https://github.com/terraforming-mars/terraforming-mars/pull/6036

**Comment by kberg** [comment]
OK #6459 resolved a few of these. There's still plenty of places for decks to run out of cards. I'm sure many of them are still in the most common paths. But it's a decent start.
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/1d1a62cb-3fc8-4bcc-ba7b-a1f2d679312e)

**Comment by kberg** [comment]
I don't think this is done, but I'm going to close the issue because I lost the thread of what needs to happen next. The issue continues to exist, I'm sure. In the end there's not much to do when the draw pile is exhausted I suppose?
