### ISSUE TITLE
Unable to reverse move

### ISSUE THREAD

**Issue by Applesgary** [terraforming-mars/terraforming-mars#5190]
Hi, can you add a feature to reverse a move on terraforming mars? I made two huge mistakes in the game unfortunately cants reverse the moves. 

Also it may be beneficial to add a “are you sure” prompt for card selection at the start of the round, as two times I clicked on confirm when some of the cards I was planning to buy were not highlighted.

thanks!

**Comment by kberg** [comment]
@Applesgary there's an Undo feature you can set up for a game. It's not great, because for instance you can't undo your second action, just your first one. It also allows people to cheat by letting them draw cards, not liking what they drew, and executing an undo.

I'm slowly working on something that enables a better scenario, but it'll still take some time.

**Comment by kberg** [comment]
There are many other bugs tracking undo issues.
