### ISSUE TITLE
Greeneries placed in final phase after a 63 TR solo win are not granting O2/TR bumps

### ISSUE THREAD

**Issue by amulder87** [terraforming-mars/terraforming-mars#5238]
The game creator has commented that the oxygen track should be advanced and a TR granted as a result from any greeneries placed during the final greenery placement phase after a solo win pursuing the 63 TR win condition. Additionally, raising the oxygen track could raise other terraforming parameters due to bonuses, and they should also grant TR. Post seen here: https://boardgamegeek.com/thread/2042802/article/29775592#29775592

Re-stating the example given there: greeneries placed in the final placement phase should grant an oxygen bump + TR. Hypothetically, that could also grant a temperature raise + TR at the oxygen breakpoint, which could grant an ocean + TR at the temp breakpoint, which could grant plants from placement, which could grant be enough for another greenery + oxygen + TR.

In a recent game, I placed a greenery in the final phase while at 13 oxygen, and the oxygen track didn't advance or grant a TR. https://terraforming-mars.herokuapp.com/the-end?id=pae4d5dcc8845

**Comment by kberg** [comment]
Thanks for the report.

That comment above was made in August 2018. In September 2018, Fryx wrote this:

> Directly after production is the solar phase, and at the start of the solar phase you check if you've won the game by having 63 TR. In final scoring you may place greenery tiles as normal, and these might possibly raise the oxygen, giving additional TR, but those TR steps are not counted towards winning, only towards your final score.

https://boardgamegeek.com/thread/2054524/article/29929752#29929752

Which is the source used for the unofficial FAQ: https://github.com/kberg/terraforming-mars-faq/wiki#in-the-tr-solo-variant-from-prelude-what-is-included-in-your-game-end-tr-to-reach-the-goal-63-tr

**Comment by kberg** [comment]
I believe this additional information makes closing this bug the right thing. Feel free to add comments if you disagree. I can always reopen it.

**Comment by amulder87** [comment]
The issue I'm reporting that in the final scoring, the greenery I placed did not raise the oxygen nor grant additional TR, which is restated in the quote above as something that should happen:
>and these might possibly raise the oxygen, giving additional TR, but those TR steps are not counted towards winning, only towards your final score.

The clarification he's making there in the September comment is that greeneries placed in the final phase aren't able to allow you to win when you otherwise would have lost, since the game victory check has already occurred. E.g. if there was room on the oxygen track and you ended gen 12/14 with only 62 TR, you've immediately lost the game and don't get a greenery placement phase. If you had 63 TR though, you've won the game, get a final greenery placement, and that placement plus any additional side effects like in the example I posted above should all grant track bumps/TR as well.

**Comment by kberg** [comment]
I see.

I think this is actually simple to fix since the app no longer lets you place final greenery if you haven't met the solo game conditions.

**Comment by amulder87** [comment]
> I see.
> 
> I think this is actually simple to fix since the app no longer lets you place final greenery if you haven't met the solo game conditions.

That makes sense to me, thank you for the quick fix!

**Comment by kevinb9n** [comment]
Sigh. Didn't see this quickly enough.

@kberg here's where we worked this out: https://github.com/terraforming-mars/terraforming-mars/issues/2055#issuecomment-820689063

It was a long and insane process to get rule clarity about this. It took a lot of effort but I was finally convinced we achieved it. Part of that was Jacob *recanting* the comment that's being quoted above in *this* new bug thread we're in now.
https://boardgamegeek.com/thread/2611160/article/37132579#37132579

I hate linking to that thread because I look like a moron in it, but whatever, that's how confusing the situation was.

Now, your PR description is correct: it *IS* okay to get TR during final greenery placement. But placing greenery won't raise the oxygen so you're not getting it *that* way.

**Comment by amulder87** [comment]
Wow that comment years later is really shocking to me. I'm not really sure I fully understand the thread even after re-reading it a dozen times now. It seems like he's saying that getting an O2 bump is now unofficially what he'd prefer rather than it being officially correct, and also unofficially thinks heat conversion in the final phase makes sense for the same reason. I, personally, am on board with the final greeneries being worth O2 because it just.. makes sense to me, but having an extra heat production phase that you can utilize too is weird to me because it never existed before. I don't know how to unpack this nonsense anymore lol.

**Comment by kevinb9n** [comment]
That's how I felt through the whole thing. :-)

His comment about heat was obviously non-canon so I took his nearby comment about how it seemed to him greeneries should still raise oxygen as non-canon too... it's not what got printed so I think his intention was to stick to that.

(It's fitting enough that plants are the only thing you can still use in the endgame, because plants have no award related to them.)

**Comment by amulder87** [comment]
Given all that, I'm good with just closing this. Thank you both for your responses and sorry for making extra work here!

**Comment by kberg** [comment]
Let me make sure I understand. The original behavior was correct all along? Because the new behavior has been deployed. It'll be easy to roll it back.

**Comment by kberg** [comment]
This was not actually deployed. Safe to close.
