### ISSUE TITLE
Allow player to spend 8 heat when temperature is at maximum

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#5265]
This option is only useful as a stalling tactic.

It's important to get the user experience right so that players know this is a stall tactic, and not actually going to give the player 1TR.

**Comment by kevinb9n** [comment]
So one idea I had is a submenu called something like "apparently useless actions", which you'd mostly only bother opening up when you want to stall. And anything like this that seems to have extremely little value would go in there but still be usable if desired...

A pretty useful variation would be if I could also move actions in there on purpose (just for the current generation). Like, I've already decided I won't be using Industrial Center this gen. If I could move it in there, then I'd be at less risk of accidentally passing when there were still actions I *did* want to play (since it would start to feel weird to pass while the take-a-card-action submenu is still there).

Dunno if these ideas are helpful, just sharing em.

**Comment by kberg** [comment]
Prototype for Asteroid Standard Action:

![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/273c7ada-04e8-4aa0-919f-7b7554307820)

This isn't 8 heat, but it's a good start.

**Comment by kberg** [comment]
@kevinb9n should the same stall tactic apply to 14MC? Or should it just be 8 heat? Same for all the MC-based projects?

**Comment by kevinb9n** [comment]
Yeah, indeed. Asteroid, Aquifer, and Air-Scrapping.

**Comment by kberg** [comment]
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/44064290-130b-484d-9cfa-c9726e27aeda)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/aebc7489-7ebf-45c8-801c-a8b0fed72f6c)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/4a558b5d-9603-46c6-898e-694c2cdbbfc6)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/c6d3eceb-27db-4ff4-9ffe-e1f80eab1729)

**Comment by kberg** [comment]
A similar warning here would not be bad: 
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/22ad0e3b-615f-4a9d-b403-ad0c0cdb5f3c)

but that's where the slippery slope begins.

**Comment by kberg** [comment]
This is in general, fixed.
