### ISSUE TITLE
Timeframe for game purges

### ISSUE THREAD

**Issue by Dienekes7** [terraforming-mars/terraforming-mars#5362]
Hi,

I love this game on Heroku, having found it by chance a few months ago. I love the ease of play, the design and would be happy to pay to play this great version of the complete game, which is somewhat lacking in other formats. 

I have racked up about 30 games with mates from NZ and from the USA (west coast) and have just started our 2nd 4 player game featuring the aforementioned NZ and USA players, plus another from the Czech Republic. We generally fly through games and always complete them. So, I was a little concerned on Monday to see that games will now be purged in about 10 days. Given our time differences (18 hours to West Coast USA to Sydney) I am afraid that our games will be lost near to the end of a game. 

I can understand you wanting to purge games from your server that are not finished to create more room. However, would you please consider 30 days, or even 20 days to finish the game. We can manage that. Or, as a possible alternative, give consideration to extending the time for games that you can see are moving along and have not sat there unmoving for days on end. 

If those are not alternatives, is there another way to play this which bypasses the game purge timeframe?

Top notch game!

thanks, Dienkes7

**Comment by kberg** [comment]
Thanks for writing. I'm sorry we can't store it for longer.

Games have been purged in ten days for as far back as I can recall (with an exception I'll explain below.) The only difference is that the app tells you about it.

The reason the rate has a limit at all is because we need to manage disk space carefully. I broke our database purge last year and the whole thing went down, right in the middle of break at the end of December.

You do have the option of hosting yourself (see https://github.com/terraforming-mars/terraforming-mars/wiki/Heroku-Setup) and (https://github.com/terraforming-mars/terraforming-mars/wiki/Docker-Setup), and setting `MAX_GAME_DAYS` (see https://github.com/terraforming-mars/terraforming-mars/wiki/dot-env) Hosting on Heroku used to be trivial and free. Now it's trivial and a few dollars per month.

Another option is that we upgrade our Heroku server to the next tier, which is ~$40USD/mo over what we're currently paying. That's too cost prohibitive, and before you ask, we're not accepting financial contribution.

That said I have been considering increasing the purge time. However, I have another project idea which might double disk space consumption, and I'd like to rule that out before considering more time.

**Comment by Dienekes7** [comment]
Thank you so much for your quick reply and explanation. Totally understand the reasons and did not notice the purge before; we must play our games quickly!  The current 4 player is a likely goner though, 28 hours left and 2 parameters have barely moved!

Thank you also for the hosting options. I'll have a look at one of them, I'm not that IT savvy but I'll nut it out. 

I look forward to any changes you may be able to make with your project idea. Until then, we'll keep trying to play quickly.

Cheers

**Comment by kberg** [comment]
https://discord.com/channels/737945098695999559/743789409396195329/1075276318876389466

>  The server has behaved pretty reliably these last couple of months with the exception of that awful break at the end of the year.,The database seems to be in a reliable state, so, starting immediately, **you have five more days to finish all async games, for a total of fifteen days.** This includes the games currently in play.

**Comment by Dienekes7** [comment]
Very much appreciated. Thank you so much. 15 days should be doable. 

We were discussing how we could do the games faster, lose turmoil, put on World Govt etc, but 15 days is very good.

thanks again.

**Comment by kberg** [comment]
Keep enjoying the games.

**Comment by aloisdg** [comment]
Start self hosting. You can use a server or your own computer with port forwarding. A rpi should be enough if you have one.

Self-hosting is the key.

Meanwhile I like that:

> give consideration to extending the time for games that you can see are moving along and have not sat there unmoving for days on end.

Nothing move at all in X days? ok purge. We can even short the time with this.

Another idea to explore is to add an [increment clock](https://en.wikipedia.org/wiki/Chess_clock#Timing_methods) of some kind. You have x days to finish the game, but as long as you play you gain x hour bonus / move.

**Comment by aloisdg** [comment]
An example from framapad:
![image](https://user-images.githubusercontent.com/3449303/220796047-bcb3632c-5808-4584-b99d-0ebcb960dc69.png)


> Delay before deletion

> Your pad will be deleted if it is not edited in about 6.9 days. Please edit or export your pad if you need to save your work.

**Comment by kberg** [comment]
Thanks for the idea. This is on the front page of our git repo

> NOTE: This site is restarted daily. A multiplayer game will remain available for 10 days, after which it will be flushed from the database. Unfinished solo games are flushed after one day. We continue to make stability and scalability improvements in step with growth and popularity, but to make sure your game remains, we highly recommended to host your own web server.

That last part is what I wanted to get at: if it's really important that your game sticks around, then host your own server. Heroku is no longer free, but I hope is an affordable cost for enjoying their hobby.
