### ISSUE TITLE
"No Player has played Van Allen" when trying to claim Specailist

### ISSUE THREAD

**Issue by nimbusscale** [terraforming-mars/terraforming-mars#5572]
When trying to claim the Specialist milestone there was a pop-up saying "No Player has played Van Allen". After clicking the link nothing happened and I tried to claim the milestone again with the same results. I then played another card and ended my turn. After I ended my turn I saw that the milestone was claimed. It didn't take the 8 MC for purchasing the milestone. The claim milestone action, not the second action taken did not show up in log. And looking in the log looks of a bit as off in general. Some log entries from Generation 1 shows up in Generation 2. 

It looks like Van Allen is related to the CEO expansion, but that expansion was not selected.We abandoned the game after that.

See screenshots here: https://imgur.com/a/KW47OmY

Player game link: https://terraforming-mars.herokuapp.com/player?id=p5d2f059b24bc

**Comment by pavel-saladukha** [comment]
Same happened here - https://terraforming-mars.herokuapp.com/the-end?id=s82f2c4942c42

**Comment by nimbusscale** [comment]
Playing another game and we ran into the same situation with the Planner, so it's not specific to just the Specialist milestone.

**Comment by JacobORiordanRoss** [comment]
Similar situation here: https://terraforming-mars.herokuapp.com/the-end?id=p9e96d1b9eb0c

**Comment by lizthegrey** [comment]
The problem is here:

https://github.com/terraforming-mars/terraforming-mars/blob/aeb048caba64cc038725848bfbaa4f9e36f0189f/src/server/Player.ts#L1399-L1400

`getCardPlayer()` is assumed to return `undefined` if the card has not been played, but instead it throws the exception if the card is not being played; either the callsite needs a catch() around it or the function needs to return undefined if the card has not been played.

**Comment by kberg** [comment]
Thanks for all the reports. A fix went out a few days ago, with a second update today that fixed existing games.
