### ISSUE TITLE
Ares version of deimos doesn't actually give adjacency bonuses

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#5575]
https://discord.com/channels/737945098695999559/742721510376210583/1093921763425001492
" [Promo] Add Ares version of Deimos Down. "   ares version of deimos doesn't actually give adjacency bonuses. it places aresy looking card but it functions identical to regular  promo deimos.

**Comment by d-little** [comment]
This is going to take some considerable additional tests, since it's working for me via manual testing.

Currently the test only makes sure that the tile grants adjacent bonuses, doesnt actually place tiles/check outcomes.

I'll put together tests to:
* player1 plays deimos, places
  * player1 places tile next to DD, no Asteroid card
  * player1 Places tile next to DD, 1 Asteroid cards
  * player1 Places tile next to DD, 2 Asteroid cards
* player2 places deimos, 
  * player1 places tile next to DD, no Asteroid card
  * player1 Places tile next to DD, 1 Asteroid cards
  * player1 Places tile next to DD, 2 Asteroid cardsplayer1 repeats above steps
* player2 places deimos, 
  * player2 has the asteroid cards,
  * player1 places next to DD, but has no asteroid cards

Some more coverage of all the edge cases to see when/where this isnt being granted

**Comment by d-little** [comment]
Im still unable to recreate this in testing, either automated or manual.  I'll do some more digging but will probably need to mark this as stale until it pops up in a new report

**Comment by kberg** [comment]
Let's close it.
