### ISSUE TITLE
Misleading graphical information at the moon global parameter tracks

### ISSUE THREAD

**Issue by Borbarad2** [terraforming-mars/terraforming-mars#5631]
In our group and with several guest players this graphical issue is arising each time in a moon expansion game: The bonuses for the moon global parameter are too far away from their global parameter tracks. Thus it looks like that the titanium production bonus belongs to the road infrastructure:

![grafik](https://user-images.githubusercontent.com/105346182/235094301-49052596-1306-4f68-917d-47c4c35713d1.png)

Suggestion for solving the issue: Moving the Bonus icons closer to their tracks.

**Comment by kberg** [comment]
What I was asking for @Borbarad2 was the information that comes from the Report A Bug UI element. I want to know which browser you're using, etc. Can you please get that information? Thanks.

**Comment by Borbarad2** [comment]
Version: 0292905, built at Sun, 16 Apr 2023 04:39:12 GMT
Browser: Firefox 112

**Comment by maserion** [comment]
On 8yh January 2022, when you compressed moon map you removed arrows next to global parameter tracks.
https://github.com/terraforming-mars/terraforming-mars/commit/e51515a1db2ed56f7bd7173b3da9a86959015bbe?diff=split

Images may look the same (due to background), but when you paste them to MS Paint, background goes black and now arrows on previosu version are visible.

1st image - current version
2nd image - previous version
![image](https://github.com/terraforming-mars/terraforming-mars/assets/18551094/dd454f26-2662-485e-b166-ef48b7c1e71e)

**Comment by kberg** [comment]
Good research! Thank you.

**Comment by Borbarad2** [comment]
So, could you change something here to make it more clear?
Remove the arrows, so that the bonus indicator move closer to the tracks?? Any suggustion for improving?

**Comment by Borbarad2** [comment]
Top. Great!
