### ISSUE TITLE
Bizarre card passing order bug

### ISSUE THREAD

**Issue by Maelstrom1** [terraforming-mars/terraforming-mars#6707]
https://terraforming-mars.herokuapp.com/spectator?id=s66788a5b5fd9

unsure how to best describe this, except the first 2 card passes during draft went the opposite direction as expected, based on the names, while the 3rd and final one went the correct way, leading to some weird outcomes. 

to clarify, if players 1-4 are A, B, C, and D, and the game says player A is passing to player B, the order of the hand is A, D, C, D

**Comment by Maelstrom1** [comment]
oops just realized there was a report a bug option:
full details 
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s66788a5b5fd9",
  "version": "d8ab047",
  "builtAt": "Sun, 02 Jun 2024 16:08:59 GMT",
  "browser": "Firefox 126",
  "language": "en",
  "experimental_ui": false
}

**Comment by Erostal** [comment]
Jumping on this because we also just experienced an issue with drafting order. The displayed drafting pass order didn't seem to be followed (e.g. game said I was passing to Corbin, passed the other way to Nadeem instead).

Also in our four player game we got a card back from our initial hand (e.g. the last card I drafted was one of my initial four choices).

It may have something to do with a recent patch, as we didn't see this issue on our May 27th game (though that was 5 players vs 4).

Our game details:
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s37d5c4994c72&noredirect=",
  "color": "orange",
  "step": 523,
  "version": "d8ab047",
  "builtAt": "Sun, 02 Jun 2024 16:08:59 GMT",
  "browser": "Firefox 126",
  "language": "en",
  "experimental_ui": false
}

I'm either missing where it used to say Game ID, but here's a link to our game:
https://terraforming-mars.herokuapp.com/the-end?id=p603fb51ebbf6

**Comment by Maelstrom1** [comment]
every generation, consistently.
it also reversed direction when draft direction changed as well

**Comment by Erostal** [comment]
Same with us - every generation where we drafted, so just not the first

**Comment by kberg** [comment]
Thanks. I see the issue. See, before I started working on drafting, there were no tests for drafting. It was pretty brittle. So I wrote some decent tests.

But I only wrote tests for a 2-player game, in which case order never really matters. I never wrote a test for a 3-player game. So this has a 3-player game tested, and I think we should be OK.
