### ISSUE TITLE
Preludes not visible at start of game

### ISSUE THREAD

**Issue by yarukishi** [terraforming-mars/terraforming-mars#7012]
I started a new game with preludes, Venus next 3 starting corps, and a random map and awards. The prelude cards didn’t populate, even on refresh.

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=se9cc2f8f9e2d",
  "color": "orange",
  "step": 1,
  "version": "98529c9",
  "builtAt": "Sat, 05 Oct 2024 14:25:08 GMT",
  "browser": "Safari 17",
  "language": "en",
  "experimental_ui": false
}
![IMG_0024](https://github.com/user-attachments/assets/2556985e-f17e-43d8-b443-87cb3bb41ec8)

**Comment by kberg** [comment]
@maserion I am pretty confident this is related to the recent change.

In Game.ts

```
if (gameOptions.startingPreludes !== undefined) {
    player.dealtPreludeCards.push(...preludeDeck.drawN(game, gameOptions.startingPreludes));
}
```

Does not work because of the `?` in `GameOptions`.

This should not have been an "if not undefined" but, if it is not undefined, it should be the default value.

Here are some tests you can add to Game.spec.ts:

```
  it('Deal preludes when starting preludes is undefined', () => {
    const player = TestPlayer.BLUE.newPlayer();
    Game.newInstance('gameid', [player], player, {preludeExtension: true, startingPreludes: undefined});
    expect(player.dealtPreludeCards).has.lengthOf(4);
  });

  it('Deal preludes when starting preludes is defined, 3', () => {
    const player = TestPlayer.BLUE.newPlayer();
    Game.newInstance('gameid', [player], player, {preludeExtension: true, startingPreludes: 3});
    expect(player.dealtPreludeCards).has.lengthOf(3);
  });

  it('Deal preludes when starting preludes is defined, 5', () => {
    const player = TestPlayer.BLUE.newPlayer();
    Game.newInstance('gameid', [player], player, {preludeExtension: true, startingPreludes: 6});
    expect(player.dealtPreludeCards).has.lengthOf(6);
  });
```

**Comment by maserion** [comment]
Hello,

The issue is related to the values provided on the main screen for the 'Starting Prelude' option. If the value entered here is empty, 0, or negative, no cards are dealt to the players' hands. The same behavior occurs for the 'Starting CEOs' option when its value is empty, 0, or negative.

Update:
The value for preludes is now set to 4 if the input is undefined or less than 2.
Similarly, the starting value for CEOs has been set to ensure at least 1 card is always dealt, even if the input is less than 1.
I have also adjusted the tests accordingly for both preludes and CEOs to reflect these changes.

**Comment by yarukishi** [comment]
Thanks for the update. When I activated the Prelude expansion for that game, the UI didn’t add the line to configure the number of prelude cards. That probably means that the value was blank, so this would fix the issue.
