### ISSUE TITLE
prelude underground settlement fizzled?

### ISSUE THREAD

**Issue by phillipfung3** [terraforming-mars/terraforming-mars#7073]
![image](https://github.com/user-attachments/assets/97aacf8e-4047-4ca2-b86c-efbac8bd98ea)

hmm sorry but what does this actually mean?

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s9f8070a6705c",
  "color": "green",
  "step": 8,
  "version": "ebb069e",
  "builtAt": "Fri, 01 Nov 2024 15:27:41 GMT",
  "browser": "Chrome 130",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
https://boardgamegeek.com/thread/1705209/official-faq-rules-clarifications says

[q]New rule! If you try to play a prelude card and it turns out to be unplayable for any reason, you must prove this to your opponents, discard it back to the box, and gain 15 MC.[/q]

This was originally described as a prelude _fizzling_. We don't require proof, since the application already basically knows. (Unless it's a mistake, in which case 😱

**Comment by kberg** [comment]
That said, if the map was in a particular setup I could see the prelude fizzling, though incorrectly. Right now it determines whether the city space follows normal excavation rules, which has to do with where your excavation markers [i]already are[/i]. So, yes, this was probably a bit of an error.

**Comment by phillipfung3** [comment]
yep I kinda figured it would happen if there is no legal space to place a city
but then it doesnt make sense if the map is practically empty lol

If the coding behind becomes it have to place a city where there is an excavation marker then yep I can see how this happened

**Comment by kberg** [comment]
Yeah. It's an easy fix. Thanks, good catch. Sorry about the bug!
